### ISSUE TITLE
Wallpaper update conflict

### ISSUE THREAD

**Issue by ToJen** [whizzzkid/bing-wallpapers-for-linux#10]
I use Ubuntu 16.04. I have an app called Wallch that changes the wallpaper at specified intervals of time. When that is launched on startup, bingwallpaper isn't able to make an changes to the current desktop wallpaper.

**Comment by whizzzkid** [comment]
This is weird, I am not able to repro this issue. Can you explain more how to make this work.

**Comment by whizzzkid** [comment]
Lack of Info
