### ISSUE TITLE
Missing a Zesty branch

### ISSUE THREAD

**Issue by dennisTGC** [whizzzkid/bing-wallpapers-for-linux#12]
Im running Zestly, but I'm missing a http://ppa.launchpad.net/whizzzkid/bingwallpaper/ubuntu/dists/zesty entry..

**Comment by atiensivu** [comment]
Artful now too. :) Can still use the older entries though.

**Comment by whizzzkid** [comment]
Turns out I just had to flick a switch on the recipe. It should be available once the daily build runs. 

Ref: https://code.launchpad.net/~whizzzkid/+recipe/bingwallpaper-daily

**Comment by dennisTGC** [comment]
Excellent, worked great on Artful! thanks!
