### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ghost** [whizzzkid/bing-wallpapers-for-linux#16]
Hi, 

First thanks for this, it works nicely and I really enjoy having Bing pic of the day as wallpaper automatically. 

Sometimes I wonder what the image displays and I would like the `copyright` somehow overlaid on the picture. I already use conky to overlay some infos on my desktop, so I was wondering if you could change the output and save the copyright with the picture (i.e. foo.jpg and foo.txt), maybe as an option

Regards, 

Régis.

**Comment by whizzzkid** [comment]
I guess by copyright you're referring to the image information, like artist name and image captions. How about you overlay this on the image before saving?

**Comment by ghost** [comment]
Yes let me illustrate (with my patch, some conky and today picture):

![capture d ecran de 2018-01-24 19-15-42](https://user-images.githubusercontent.com/199613/35349360-fe8a943a-013a-11e8-961e-5403692f603b.png)

The advantage of not doing overlay in your script is that it let peoples free to use it (or not). I'm not sure everyone want this text

**Comment by whizzzkid** [comment]
I understood what you were trying to do here. This would require you to configure a conky widget to get get text from this file and display. However not everyone uses conky, so there should be an option to either create a conky widget along with this script or load the caption written on the image.

I believe it can be as simple as:

`convert -pointsize 36 -fill white -draw 'text <x>,<y>' "<caption>" <img>`

**Comment by ghost** [comment]
My request / PR changes nothing on the way your script works, there's only a new text file generated. But if you think a more complicated (but more generic) way is best, that's OK with me, my wish is just to have a way to read this "copyright" without browsing bing.com every times :)

**Comment by ghost** [comment]
Hi Nishant, 

Thanks for the merge :+1:  This can be closed

Regards

----

For "future reader", here's a sample usage in `~/.conkyrc`:

```
alignment bottom_left

gap_x 10
gap_y 10

TEXT
${color EAEAEA}${font Ubuntu:pixelsize=12}${exec cat "$(ls -1t ~/Pictures/Bing/*.txt | head -1)"}
```

One could also, as you suggested, use imagemagick (using the cron setup) to perform the overlay
