### ISSUE TITLE
install error on 16.10

### ISSUE THREAD

**Issue by dennisTGC** [whizzzkid/bing-wallpapers-for-linux#3]
Im getting this while installing it on 16.10. I don't think i had this error on 16.04, so there might be some changes in how stuff gets started? I wouldn't know, im a newbie. I just added bingwallpaper to my startup applications.

Registering as startup application...
/var/lib/dpkg/info/bingwallpaper.postinst: 9: /var/lib/dpkg/info/bingwallpaper.postinst: cannot create /home/dennis/.config/autostart/bingwallpaper.desktop: Directory nonexistent
dpkg: error processing package bingwallpaper (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 bingwallpaper

**Comment by whizzzkid** [comment]
hmmm, lemme have a look, I am not on on 16.10

**Comment by whizzzkid** [comment]
This has been fixed in last commit. It should not happen again.

**Comment by dennisTGC** [comment]
excellent, thanks!

**Comment by rickmacgillis** [comment]
It's baaaaack! I'm using the releases from the PPA at https://launchpad.net/~whizzzkid/+archive/ubuntu/bingwallpaper and whenever I update my software, I get the following output as an error.

```
Errors were encountered while processing:
 bingwallpaper
E: Sub-process /usr/bin/dpkg returned an error code (1)
A package failed to install.  Trying to recover:
Setting up bingwallpaper (0.5-0~20~ubuntu20.04.1) ...
/root
Registering as startup application...
/var/lib/dpkg/info/bingwallpaper.postinst: 11: cannot create /root/.config/autostart/bingwallpaper.desktop: Directory nonexistent
dpkg: error processing package bingwallpaper (--configure):
 installed bingwallpaper package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 bingwallpaper
```

**Comment by RaymondSHANG** [comment]
> It's baaaaack! I'm using the releases from the PPA at https://launchpad.net/~whizzzkid/+archive/ubuntu/bingwallpaper and whenever I update my software, I get the following output as an error.
> 
> ```
> Errors were encountered while processing:
>  bingwallpaper
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> A package failed to install.  Trying to recover:
> Setting up bingwallpaper (0.5-0~20~ubuntu20.04.1) ...
> /root
> Registering as startup application...
> /var/lib/dpkg/info/bingwallpaper.postinst: 11: cannot create /root/.config/autostart/bingwallpaper.desktop: Directory nonexistent
> dpkg: error processing package bingwallpaper (--configure):
>  installed bingwallpaper package post-installation script subprocess returned error exit status 2
> Errors were encountered while processing:
>  bingwallpaper
> ```
In my case (ubuntu 20), the error is because the directory '/root/.config/autostart' does not exist.
I solved it by the following steps:
```bash
sudo mkdir /root/.config
sudo mkdir /root/.config/autostart
sudo apt-get install bingwallpaper
```
Hopefully this will help,
