### ISSUE TITLE
The .desktop file gets messy with updates

### ISSUE THREAD

**Issue by ghost** [whizzzkid/bing-wallpapers-for-linux#4]
Because of the `>>` [here](https://github.com/whizzzkid/bing-wallpapers-for-linux/blob/master/debian/postinst#L9), the file `~/.config/autostart/bingwallpaper.desktop` becomes messy after a  few updates:

```
[Desktop Entry]
Type=Application
Exec=sh /usr/bin/bingwallpaper
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Bing Wallpaper
Comment=Bing Pic of the day as wallpaper.
[Desktop Entry]
Type=Application
Exec=sh /usr/bin/bingwallpaper
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=Bing Wallpaper
Comment=Bing Pic of the day as wallpaper.
# ...
```

Another point, this file is owned by `root:root` but sits in _user land_, that's incorrect I think.

---

PS: :+1: for this tool, I really like it.

**Comment by whizzzkid** [comment]
<img src="http://i.imgur.com/vB9B5.gif">

I should remove the desktop entry, [This](https://github.com/whizzzkid/bing-wallpapers-for-linux/commit/bfc97700994ef4bbc46f835c95f699ba17f920fb) should resolve it.

For some reason on mint, It shows me as the owner of this file. I never wondered that it should show this file to be owned by root. Lemme dig deeper on this.

Thanks :-)

**Comment by ghost** [comment]
It's fixed, but I did notice something:

    /var/log/syslog.7.gz:Dec 19 06:38:27 xxxxxxxxxxx bingwallpaper.desktop[3842]: /usr/bin/bingwallpaper: 93: /usr/bin/bingwallpaper: Syntax error: "(" unexpected (expecting "fi")

That was causing the autostart process to fail. I think this is because of the `sh` in the autostart file:

    regis@xxxxxxxxxxx:~$ sh /usr/bin/bingwallpaper
    /usr/bin/bingwallpaper: 93: /usr/bin/bingwallpaper: Syntax error: "(" unexpected (expecting "fi")

Removing the `sh` fixed the issue for me

**Comment by whizzzkid** [comment]
This is fixed now. Closing this issue.
